# Generated by Django 3.1.7 on 2021-03-20 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supersub', '0002_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_name',
            new_name='name',
        ),
    ]
