# Generated by Django 3.1.7 on 2021-03-21 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supersub', '0003_auto_20210320_1916'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supersub.category')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supersub.product')),
            ],
        ),
    ]
