# Generated by Django 3.1.7 on 2021-03-27 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supersub', '0003_auto_20210327_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='categories',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
