# Generated by Django 3.1.7 on 2021-03-27 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supersub', '0004_auto_20210327_1505'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='fatty_acids',
            new_name='fat',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='saturated_fatty_acids',
            new_name='saturated_fat',
        ),
    ]
