# Generated by Django 3.1.7 on 2021-03-27 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supersub', '0005_auto_20210327_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='categories',
            field=models.TextField(null=True),
        ),
    ]
