# Generated by Django 3.1.7 on 2021-03-21 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supersub', '0005_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='favorites',
            field=models.ManyToManyField(to='supersub.ProductCategory'),
        ),
    ]
