# Generated by Django 3.1.7 on 2021-03-21 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supersub', '0006_user_favorites'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='products',
            field=models.ManyToManyField(to='supersub.Category'),
        ),
        migrations.AlterField(
            model_name='user',
            name='favorites',
            field=models.ManyToManyField(to='supersub.Product'),
        ),
        migrations.DeleteModel(
            name='ProductCategory',
        ),
    ]
