# Generated by Django 3.1.7 on 2021-04-01 04:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supersub', '0006_auto_20210327_1932'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_origin', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('url', models.URLField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(default=9999999999, on_delete=django.db.models.deletion.CASCADE, to='supersub.category'),
        ),
    ]
