# Generated by Django 3.1.7 on 2021-03-21 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supersub', '0010_auto_20210321_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='fatty_acids',
            field=models.DecimalField(decimal_places=3, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='salt',
            field=models.DecimalField(decimal_places=3, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='saturated_fatty_acids',
            field=models.DecimalField(decimal_places=3, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='sugar',
            field=models.DecimalField(decimal_places=3, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='url',
            field=models.URLField(null=True),
        ),
    ]
