# Generated by Django 3.1.7 on 2021-03-21 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supersub', '0011_auto_20210321_1518'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_category',
            field=models.ManyToManyField(through='supersub.ProductCategory', to='supersub.Category'),
        ),
    ]
