# Generated by Django 3.1.7 on 2021-03-21 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supersub', '0013_auto_20210321_1808'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductCategory',
            new_name='Products',
        ),
        migrations.RenameField(
            model_name='favorites',
            old_name='favorites',
            new_name='products',
        ),
        migrations.RemoveField(
            model_name='product',
            name='compose_product_category',
        ),
        migrations.RemoveField(
            model_name='user',
            name='compose_favorites',
        ),
        migrations.AddField(
            model_name='product',
            name='product_category',
            field=models.ManyToManyField(through='supersub.Products', to='supersub.Category'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_products',
            field=models.ManyToManyField(through='supersub.Favorites', to='supersub.Products'),
        ),
    ]
